### ISSUE TITLE
asyncio.base_futures.InvalidStateError: invalid state

### ISSUE THREAD

**Issue by DaWe35** [unicorn-data-analysis/unicorn-binance-websocket-api#18] opened 2019-06-16 10:25 UTC
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you using the module on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Hardware
- [ ] Raspberry Pi

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)

#### Python Version Requirement
- [x] I am using Python 3.5.3 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
3.6
```

#### UNICORN Binance WebSocket API Version?
```
latest
```

#### Description of your issue

Sorry, I don't know what is this. It just throws a bug after some hours running. Any ideas? If it don't help, feel free to delete the issue.
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 142, in _create_stream_thread
    loop.run_until_complete(binance_websocket_api_socket.start_socket())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_socket.py", line 62, in start_socket
    received_stream_data_json = await websocket.receive()
  File "/home/user/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_connection.py", line 183, in receive
    received_data = await self.handler_binance_websocket_api_manager.websocket_list[self.stream_id].recv()
  File "/home/user/.local/lib/python3.6/site-packages/websockets/protocol.py", line 441, in recv
    self._put_message_waiter.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
```

**Comment by bithon** [comment] 2019-06-16 20:39
Hi David!
This happend once or every time you start it after some hours?
The error indicates, that receive()  is used outside of the async context manager, but i dont understand the reason. I think its good to catch the exception and log it and reset the websocket connection. Does this happen to all your connections or just to specific ones? if specific, can you provide me your settings for create_stream() please? i would like to reproduce the error...
Thanks,
Oliver

**Comment by DaWe35** [comment] 2019-06-16 21:11
It happened twice in the last 2 days, not too densely, but it is annoying to break the process. Now it has been running smoothly for 10 hours, and Inserted 215 208 800 rows to MySQL :)  :)
Here is a detail from my code:
```
def sqlprint(ticker, depth, pair, now): # writes out the ticker & depth data to mySQL
	ticker = json.loads(ticker)
	depth = json.loads(depth)

	sql = "INSERT INTO ticker (stream, timestamp, close) VALUES (%s, %s, %s)" #write ticker last price
	#.....

	for elem in depth['data']['bids']: #write depth bids
		sql = "INSERT INTO depth (stream, timestamp, side, price, amount) VALUES (%s, %s, %s, %s, %s)"
		#.....

	for elem in depth['data']['asks']: #write depth asks
		sql = "INSERT INTO depth (stream, timestamp, side, price, amount) VALUES (%s, %s, %s, %s, %s)"
		#.....
	mydb.commit()

def progress_data(streamdata):
	if the (channel+amrket) last data inserted 1+ seconds ago:
                call sqlprint()

#......

binance_websocket_api_manager = BinanceWebSocketApiManager(progress_data) # create instance of BinanceWebSocketApiManager

# define stream channels
channels = {'depth20', 'miniTicker'}
markets = ['ethbtc', 'ltcbtc', 'bnbbtc', 'neobtc', 'qtumeth', 'eoseth', 'snteth', 'bnteth', 'gasbtc', 'bnbeth', 'btcusdt', 'ethusdt', 'oaxeth', 'dnteth', 'mcoeth', 'mcobtc', 'wtcbtc', 'wtceth', 'lrcbtc', 'lrceth', 'qtumbtc', 'yoyobtc', 'omgbtc', 'omgeth', 'zrxbtc', 'zrxeth', 'stratbtc', 'strateth', 'snglsbtc', 'snglseth', 'bqxbtc', 'bqxeth', 'kncbtc', 'knceth', 'funbtc', 'funeth', 'snmbtc', 'snmeth', 'neoeth', 'iotabtc', 'iotaeth', 'linkbtc', 'linketh', 'xvgbtc', 'xvgeth', 'mdabtc', 'mdaeth', 'mtlbtc', 'mtleth', 'eosbtc', 'sntbtc', 'etceth', 'etcbtc', 'mthbtc', 'mtheth', 'engbtc', 'engeth', 'dntbtc', 'zecbtc', 'zeceth', 'bntbtc', 'astbtc', 'asteth', 'dashbtc', 'dasheth', 'oaxbtc', 'btgbtc', 'btgeth', 'evxbtc', 'evxeth', 'reqbtc', 'reqeth', 'vibbtc', 'vibeth', 'trxbtc', 'trxeth', 'powrbtc', 'powreth', 'arkbtc', 'arketh', 'yoyoeth', 'xrpbtc', 'xrpeth', 'enjbtc', 'enjeth', 'storjbtc', 'storjeth', 'bnbusdt', 'yoyobnb', 'powrbnb', 'kmdbtc', 'kmdeth', 'nulsbnb', 'rcnbtc', 'rcneth', 'rcnbnb', 'nulsbtc', 'nulseth', 'rdnbtc', 'rdneth', 'rdnbnb', 'xmrbtc', 'xmreth', 'dltbnb', 'wtcbnb', 'dltbtc', 'dlteth', 'ambbtc', 'ambeth', 'ambbnb', 'batbtc', 'bateth', 'batbnb', 'bcptbtc', 'bcpteth', 'bcptbnb', 'arnbtc', 'arneth', 'gvtbtc', 'gvteth', 'cdtbtc', 'cdteth', 'gxsbtc', 'gxseth', 'neousdt', 'neobnb', 'poebtc', 'poeeth', 'qspbtc', 'qspeth', 'qspbnb', 'btsbtc', 'btseth', 'btsbnb', 'xzcbtc', 'xzceth', 'xzcbnb', 'lskbtc', 'lsketh', 'lskbnb', 'tntbtc', 'tnteth', 'fuelbtc', 'fueleth', 'manabtc', 'manaeth', 'bcdbtc', 'bcdeth', 'dgdbtc', 'dgdeth', 'iotabnb', 'adxbtc', 'adxeth', 'adxbnb', 'adabtc', 'adaeth', 'pptbtc', 'ppteth', 'cmtbtc', 'cmteth', 'cmtbnb', 'xlmbtc', 'xlmeth', 'xlmbnb', 'cndbtc', 'cndeth', 'cndbnb', 'lendbtc', 'lendeth', 'wabibtc', 'wabieth', 'wabibnb', 'ltceth', 'ltcusdt', 'ltcbnb', 'tnbbtc', 'tnbeth', 'wavesbtc', 'waveseth', 'wavesbnb', 'gtobtc', 'gtoeth', 'gtobnb', 'icxbtc', 'icxeth', 'icxbnb', 'ostbtc', 'osteth', 'ostbnb', 'elfbtc', 'elfeth', 'aionbtc', 'aioneth', 'aionbnb', 'neblbtc', 'nebleth', 'neblbnb', 'brdbtc', 'brdeth', 'brdbnb', 'mcobnb', 'edobtc', 'edoeth', 'navbtc', 'naveth', 'navbnb', 'lunbtc', 'luneth', 'appcbtc', 'appceth', 'appcbnb', 'vibebtc', 'vibeeth']

print('Connecting to ' + str(len(markets)) + ' market')

binance_get_kline_stream_id1 = binance_websocket_api_manager.create_stream(channels, markets)


while True:
	runsince = int(time.time() - start_time)
	runsince = str(datetime.timedelta(seconds=runsince))
	sys.stdout.write('\r ' + runsince + '  Inserted rows: ' + str("{:,}".format(all_sql_wrote)))
	sys.stdout.flush()
	time.sleep(1)
```
So the script wites out a lot of data to sql, maximum markets*41 INSERT in a second, that means 8733 row/s maximum. (some GB/day)
Now, the script runs on a Google Cloud Instance ( n1-standard-1, 1 vCPU, 3.75 GB memory), and the average CPU usage is 90%. (maybe this can be a problem?)

**Comment by bithon** [comment] 2019-06-16 21:56
On a respberry pi 3 the dev_test_non_stop.py script (~33GB/day) does not work, some connections allways died after a while and this happend only on raspberry systems. but i didnt took the time to take a deeper look to it, i was just interessted to so if it works and finaly it didnt...

We have also some virtual private servers with just 2GB but 2cores and small disks.

Honestly i think this could be a realistic reason that a coroutine gets a timeout or similar if the cpu queue gets to long for a while. with 90% cpu you are near the limit in average mode, if there is a peak. This is a screenshot of the receives rate from today:
![Screenshot_20190616_234904](https://user-images.githubusercontent.com/47597331/59569985-5c050000-9091-11e9-975e-f5f2158bbb28.png)

average receive on this system is ~700 records per second, the highest peak of today was at ~2200.

its not an affiliate link :) but i know on Hetzner you get 2 CPUs with 2 GB RAM and 20 or 30 GB HD with 20 TB traffic per month for 2,49 EUR and the api runs there very well.  

Can you do a test on your cloud sys? try to add one CPU and look, if this resolves the issue.

Anyway i will add an exception and a restart for this error to the code. If CPU resources are the reason we can add a hint to the logging message.

**Comment by bithon** [comment] 2019-06-17 15:34
The exception is handled since the latest release: 
https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api/releases
https://pypi.org/project/unicorn-binance-websocket-api/

**Comment by bithon** [comment] 2019-06-19 23:50
Was the cpu the reason?

**Comment by DaWe35** [comment] 2019-06-20 08:12
I thought it was, because I tested it with 100% workload, and it didn't crashed. But now I see, it happened again after 20 hour:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 142, in _create_stream_thread
    loop.run_until_complete(binance_websocket_api_socket.start_socket())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_socket.py", line 62, in start_socket
    received_stream_data_json = await websocket.receive()
  File "/home/user/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_connection.py", line 183, in receive
    received_data = await self.handler_binance_websocket_api_manager.websocket_list[self.stream_id].recv()
  File "/home/user/.local/lib/python3.6/site-packages/websockets/protocol.py", line 441, in recv
    self._put_message_waiter.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
```
I'll tell you if it happens again

**Comment by bithon** [comment] 2019-06-20 17:56
if you need exact 100% CPU all the time, it doesnt matter. But if you need 101% CPU all the time, than the queue of ready processes waiting for runtime is getting longer and longer. In the beginning it doesnt matter, because the queue is very short and the processes are not waiting to much time. But after a while, the backlog is too big and then processes are starting to timeout ...

https://en.wikipedia.org/wiki/Run_queue

The easiest test would be to add one extra cpu to your vps. Is this possible for you to do?

I added an exception to version 1.4.0 for this bug, could you test, if it works to catch the error and to restart the streams?

**Comment by bithon** [comment] 2019-06-20 20:26
This is an other project, also relying on websockets and they had the same issue and offer some solutions for this: https://github.com/Rapptz/discord.py/issues/1996

Could you run this on your system parallel to your code?
```
from unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager import BinanceWebSocketApiManager
import logging
import time
import threading
import os


def print_stream_data_from_stream_buffer(binance_websocket_api_manager):
    while True:
        if binance_websocket_api_manager.is_manager_stopping():
            exit(0)
        oldest_stream_data_from_stream_buffer = binance_websocket_api_manager.pop_stream_data_from_stream_buffer()
        if oldest_stream_data_from_stream_buffer is False:
            time.sleep(0.01)


# https://docs.python.org/3/library/logging.html#logging-levels
logging.basicConfig(filename=os.path.basename(__file__) + '.log',
                    format="{asctime} [{levelname:8}] {process} {thread} {module}: {message}",
                    style="{")
logging.getLogger('unicorn-log').addHandler(logging.StreamHandler())
logging.getLogger('unicorn-log').setLevel(logging.INFO)

# create instance of BinanceWebSocketApiManager
binance_websocket_api_manager = BinanceWebSocketApiManager()

# define stream channels
channels = {'depth20', 'miniTicker'}
markets = ['ethbtc', 'ltcbtc', 'bnbbtc', 'neobtc', 'qtumeth', 'eoseth', 'snteth', 'bnteth', 'gasbtc', 'bnbeth', 'btcusdt', 'ethusdt', 'oaxeth', 'dnteth', 'mcoeth', 'mcobtc', 'wtcbtc', 'wtceth', 'lrcbtc', 'lrceth', 'qtumbtc', 'yoyobtc', 'omgbtc', 'omgeth', 'zrxbtc', 'zrxeth', 'stratbtc', 'strateth', 'snglsbtc', 'snglseth', 'bqxbtc', 'bqxeth', 'kncbtc', 'knceth', 'funbtc', 'funeth', 'snmbtc', 'snmeth', 'neoeth', 'iotabtc', 'iotaeth', 'linkbtc', 'linketh', 'xvgbtc', 'xvgeth', 'mdabtc', 'mdaeth', 'mtlbtc', 'mtleth', 'eosbtc', 'sntbtc', 'etceth', 'etcbtc', 'mthbtc', 'mtheth', 'engbtc', 'engeth', 'dntbtc', 'zecbtc', 'zeceth', 'bntbtc', 'astbtc', 'asteth', 'dashbtc', 'dasheth', 'oaxbtc', 'btgbtc', 'btgeth', 'evxbtc', 'evxeth', 'reqbtc', 'reqeth', 'vibbtc', 'vibeth', 'trxbtc', 'trxeth', 'powrbtc', 'powreth', 'arkbtc', 'arketh', 'yoyoeth', 'xrpbtc', 'xrpeth', 'enjbtc', 'enjeth', 'storjbtc', 'storjeth', 'bnbusdt', 'yoyobnb', 'powrbnb', 'kmdbtc', 'kmdeth', 'nulsbnb', 'rcnbtc', 'rcneth', 'rcnbnb', 'nulsbtc', 'nulseth', 'rdnbtc', 'rdneth', 'rdnbnb', 'xmrbtc', 'xmreth', 'dltbnb', 'wtcbnb', 'dltbtc', 'dlteth', 'ambbtc', 'ambeth', 'ambbnb', 'batbtc', 'bateth', 'batbnb', 'bcptbtc', 'bcpteth', 'bcptbnb', 'arnbtc', 'arneth', 'gvtbtc', 'gvteth', 'cdtbtc', 'cdteth', 'gxsbtc', 'gxseth', 'neousdt', 'neobnb', 'poebtc', 'poeeth', 'qspbtc', 'qspeth', 'qspbnb', 'btsbtc', 'btseth', 'btsbnb', 'xzcbtc', 'xzceth', 'xzcbnb', 'lskbtc', 'lsketh', 'lskbnb', 'tntbtc', 'tnteth', 'fuelbtc', 'fueleth', 'manabtc', 'manaeth', 'bcdbtc', 'bcdeth', 'dgdbtc', 'dgdeth', 'iotabnb', 'adxbtc', 'adxeth', 'adxbnb', 'adabtc', 'adaeth', 'pptbtc', 'ppteth', 'cmtbtc', 'cmteth', 'cmtbnb', 'xlmbtc', 'xlmeth', 'xlmbnb', 'cndbtc', 'cndeth', 'cndbnb', 'lendbtc', 'lendeth', 'wabibtc', 'wabieth', 'wabibnb', 'ltceth', 'ltcusdt', 'ltcbnb', 'tnbbtc', 'tnbeth', 'wavesbtc', 'waveseth', 'wavesbnb', 'gtobtc', 'gtoeth', 'gtobnb', 'icxbtc', 'icxeth', 'icxbnb', 'ostbtc', 'osteth', 'ostbnb', 'elfbtc', 'elfeth', 'aionbtc', 'aioneth', 'aionbnb', 'neblbtc', 'nebleth', 'neblbnb', 'brdbtc', 'brdeth', 'brdbnb', 'mcobnb', 'edobtc', 'edoeth', 'navbtc', 'naveth', 'navbnb', 'lunbtc', 'luneth', 'appcbtc', 'appceth', 'appcbnb', 'vibebtc', 'vibeeth']

binance_get_kline_stream_id1 = binance_websocket_api_manager.create_stream(channels, markets)

# start a worker process to move the received stream_data from the stream_buffer to a print function
worker_thread = threading.Thread(target=print_stream_data_from_stream_buffer, args=(binance_websocket_api_manager,))
worker_thread.start()

# show an overview
while True:
    binance_websocket_api_manager.print_summary()
    time.sleep(1)
``` 

Would be interesting to see if it crashs too, if so, please send me the log file it is going to create.

**Comment by DaWe35** [comment] 2019-06-22 22:22
> Could you run this on your system parallel to your code?

Some minutes after the first start, my code crashed. I restarted my code and the given (this time I run three thread ot that). After 15 min, it crashed again.
Crashes happened then CPU was 100%, so I will double it and test.

`pip freeze > pip_freeze.tx`
```
aniso8601==7.0.0
asn1crypto==0.24.0
backports.functools-lru-cache==1.5
blinker==1.4
boto==2.44.0
certifi==2019.3.9
chardet==3.0.4
cheroot==6.5.5
Click==7.0
cloud-init==19.1
colorama==0.4.1
configobj==5.0.6
cryptography==2.1.4
distro==1.0.1
distro-info===0.18ubuntu0.18.04.1
Flask==1.0.3
Flask-RESTful==0.3.7
google-compute-engine==2.8.13
httplib2==0.9.2
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
MarkupSafe==1.1.1
more-itertools==7.0.0
mysql-connector==2.2.9
netifaces==0.10.4
oauthlib==2.0.6
pathlib==1.0.1
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==17.5.0
pyserial==3.4
python-apt==1.6.4
python-debian==0.1.32
pytz==2019.1
pyxdg==0.25
PyYAML==3.12
requests==2.22.0
PyYAML==3.12
requests==2.22.0
requests-unixsocket==0.1.5
SecretStorage==2.3.1
six==1.12.0
ssh-import-id==5.7
systemd-python==234
unattended-upgrades==0.1
unicorn-binance-websocket-api==1.3.8
urllib3==1.25.3
websocket-client==0.56.0
websockets==7.0
Werkzeug==0.15.4
```

**Comment by DaWe35** [comment] 2019-06-23 21:44
Okay, so with double CPU, my script also crashes. 
`10:36:02  Inserted rows: 8,156,622`
So that means the code runs 10 hours ago, and there were 8,156,622 rows inserted to mysql - and rows counter stucked, there are no new data. (If we count 4000/s row, that means the script ran less than an hour before stopped working).
I'm using the latest unicorn library, so the error catched successfully, there is no error message, but apart from this nothing happened. How can I auto restart the script at this point? Do we have to implement it to the unicorn lib, or do I just need it?

**Comment by bithon** [comment] 2019-06-24 09:03
thats sad, i hoped it is the reason.

I compared the pip freeze list and i think its fine... nothing striking.

did only your app die or also the script i posted?

I already implement the reconnect in the lib, if it didnt work, i have to review the code ... did it produce a log file?

Are you working with the stream_buffer or do you use the callback function?

**Comment by DaWe35** [comment] 2019-06-25 12:57
Hey!

> Are you working with the stream_buffer or do you use the callback function?

No buffer, callback used in this script. Maybe try buffer?

> I already implement the reconnect in the lib, if it didnt work, i have to review the code...

Hmm I don't know. I see reconnection works well when my connection dies, I love it, but this time, I don't know where is the issue.

There is a log from my script, later I'll run yours.

`2019-06-25 12:29:56,964 [CRITICAL] 14636 140651498125056 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:36:50,831 [CRITICAL] 14636 140651468089088 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:39:50,720 [CRITICAL] 14636 140651489732352 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:42:01,793 [CRITICAL] 14636 140651468089088 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:44:07,893 [CRITICAL] 14636 140651498125056 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:46:28,576 [CRITICAL] 14636 140651468089088 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:48:09,261 [CRITICAL] 14636 140651498125056 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:49:47,363 [CRITICAL] 14636 140651468089088 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:51:34,107 [CRITICAL] 14636 140651489732352 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e) - asyncio.base_futures.InvalidStateError - error_msg: invalid state
2019-06-25 12:51:34,846 [ERROR   ] 14636 140651468089088 unicorn_binance_websocket_api_connection: BinanceWebSocketApiConnection->await._conn.__aenter__(f3b3a0cf-fefe-4e3a-8401-70fa8e46698e, {'depth20', 'miniTicker'}, ['ethbtc', 'ltcbtc', 'bnbbtc', 'neobtc', 'qtumeth', 'eoseth', 'snteth', 'bnteth', 'gasbtc', 'bnbeth', 'btcusdt', 'ethusdt', 'oaxeth', 'dnteth', 'mcoeth', 'mcobtc', 'wtcbtc', 'wtceth', 'lrcbtc', 'lrceth', 'qtumbtc', 'yoyobtc', 'omgbtc', 'omgeth', 'zrxbtc', 'zrxeth', 'stratbtc', 'strateth', 'snglsbtc', 'snglseth', 'bqxbtc', 'bqxeth', 'kncbtc', 'knceth', 'funbtc', 'funeth', 'snmbtc', 'snmeth', 'neoeth', 'iotabtc', 'iotaeth', 'linkbtc', 'linketh', 'xvgbtc', 'xvgeth', 'mdabtc', 'mdaeth', 'mtlbtc', 'mtleth', 'eosbtc', 'sntbtc', 'etceth', 'etcbtc', 'mthbtc', 'mtheth', 'engbtc', 'engeth', 'dntbtc', 'zecbtc', 'zeceth', 'bntbtc', 'astbtc', 'asteth', 'dashbtc', 'dasheth', 'oaxbtc', 'btgbtc', 'btgeth', 'evxbtc', 'evxeth', 'reqbtc', 'reqeth', 'vibbtc', 'vibeth', 'trxbtc', 'trxeth', 'powrbtc', 'powreth', 'arkbtc', 'arketh', 'yoyoeth', 'xrpbtc', 'xrpeth', 'enjbtc', 'enjeth', 'storjbtc', 'storjeth', 'bnbusdt', 'yoyobnb', 'powrbnb', 'kmdbtc', 'kmdeth', 'nulsbnb', 'rcnbtc', 'rcneth', 'rcnbnb', 'nulsbtc', 'nulseth', 'rdnbtc', 'rdneth', 'rdnbnb', 'xmrbtc', 'xmreth', 'dltbnb', 'wtcbnb', 'dltbtc', 'dlteth', 'ambbtc', 'ambeth', 'ambbnb', 'batbtc', 'bateth', 'batbnb', 'bcptbtc', 'bcpteth', 'bcptbnb', 'arnbtc', 'arneth', 'gvtbtc', 'gvteth', 'cdtbtc', 'cdteth', 'gxsbtc', 'gxseth', 'neousdt', 'neobnb', 'poebtc', 'poeeth', 'qspbtc', 'qspeth', 'qspbnb', 'btsbtc', 'btseth', 'btsbnb', 'xzcbtc', 'xzceth', 'xzcbnb', 'lskbtc', 'lsketh', 'lskbnb', 'tntbtc', 'tnteth', 'fuelbtc', 'fueleth', 'manabtc', 'manaeth', 'bcdbtc', 'bcdeth', 'dgdbtc', 'dgdeth', 'iotabnb', 'adxbtc', 'adxeth', 'adxbnb', 'adabtc', 'adaeth', 'pptbtc', 'ppteth', 'cmtbtc', 'cmteth', 'cmtbnb', 'xlmbtc', 'xlmeth', 'xlmbnb', 'cndbtc', 'cndeth', 'cndbnb', 'lendbtc', 'lendeth', 'wabibtc', 'wabieth', 'wabibnb', 'ltceth', 'ltcusdt', 'ltcbnb', 'tnbbtc', 'tnbeth', 'wavesbtc', 'waveseth', 'wavesbnb', 'gtobtc', 'gtoeth', 'gtobnb', 'icxbtc', 'icxeth', 'icxbnb', 'ostbtc', 'osteth', 'ostbnb', 'elfbtc', 'elfeth', 'aionbtc', 'aioneth', 'aionbnb', 'neblbtc', 'nebleth', 'neblbnb', 'brdbtc', 'brdeth', 'brdbnb', 'mcobnb', 'edobtc', 'edoeth', 'navbtc', 'naveth', 'navbnb', 'lunbtc', 'luneth', 'appcbtc', 'appceth', 'appcbnb', 'vibebtc', 'vibeeth']) Status code not 101: 400
`

**Comment by bithon** [comment] 2019-06-25 21:09
hm, it catchs the error, but dont reconnect, interesting.

there is one big difference between stream_buffer and callback:
if you use the stream_buffer, then you create a separate thread which is working independent from the websocket connection and the receive function.
if you use the callback function, then the thread that execute the receive function starts your callbackcode which runs in the same thread as the websocket. so if you have a bug in your code, it kills the websocket connection ... i dont know, maybe you loose database connection for a few minutes or it slows completely down in cause of a backup ... hard to tell for me. 

i think to help you and to find the issue its the easiest and fastest way if you provide me your full code. then i can test and search. this way i just can guess :/

thats what i want to test with the script i provided you. it has the same config as you use, but runs without dependencies in the code. no other systems are involved (like DB) i just throw the receives away.... so you can check if the lib cause the problem or your code.

you could test to deactivate code in the callback function and test again, maybe there is something the causes a bug rarely and results in this error.

**Comment by DaWe35** [comment] 2019-06-25 21:54
Okay, I created a repo and uploaded my code and SQL structure here: [https://github.com/DaWe35/Flash-public/](https://github.com/DaWe35/Flash-public/)

Your script runs without error ~9 hours ago, so I guess the problem is with MySQL. I need to try it with the buffer.

**Comment by bithon** [comment] 2019-06-26 07:39
Ok, looks everything is there. I am going to test soon. Are you using mysql or mariadb? Which version? Which distribution and version?

**Comment by DaWe35** [comment] 2019-06-26 15:37
mysql  Ver 14.14 Distrib 5.7.26
Okay, I will rewrite it, that's a good idea!

**Comment by bithon** [comment] 2019-06-27 21:39
Sorry, I meant the Linux distribution...

Anyway if I have the infos, I am going to wait of the result of the stream_buffer test.

**Comment by DaWe35** [comment] 2019-06-28 13:50
Ubuntu 18.04.2 LTS
I need some days, I'm very busy nowadays, but I'll do it. Thank you!

**Comment by bithon** [comment] 2019-06-28 20:23
I added an exception to your code and made a pull request to your repo. good luck :)

**Comment by DaWe35** [comment] 2019-06-29 09:52
Wowo, thank you, I'm testing...

**Comment by aaugustin** [comment] 2019-06-30 20:57
I'm pretty sure it's a bug in websockets: https://github.com/aaugustin/websockets/issues/634

**Comment by DaWe35** [comment] 2019-06-30 22:12
Okay, so with the [try-catch block](https://github.com/DaWe35/Binance-websocket-api-to-mysql/pull/1/commits/a82e802be61ee38ebb1193ee2bd9b54962179a29), auto reconnect works well. My problem solved, thank you bithon!

Invalid state error happened when the mysql was overloaded.
Log:
```
2019-07-01 00:00:04,375 [CRITICAL] 1384 139864439629568 unicorn_binance_websocket_api_connection: binance_websocket_api_connection->receive(c881d97a-f3c3-40$
```
`1 day, 12:25:47  Inserted rows: 713,597,496` - Yeah, cool numbers :)

**Comment by bithon** [comment] 2019-07-01 08:50
Very cool! :)

To remind you: In this way you loose all data received during a down mysql database, because you have no error handling for such a case. If you work with the stream_buffer (working example: https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api/blob/master/example_stream_buffer.py) you are able to avoid such loses... just a view lines of code and you can copy paste. Just put your mysql code into the print stream buffer function to the print() section. thats all.

I would like to ask you, to run that script as it is for 2 more weeks to see if that bug is really caused the way we belief and is completely removed. I think this would help https://github.com/aaugustin/websockets/issues/634 - its the lib we are relying on for websocket operations and augustin is interested to investigate this issue.

**Comment by bithon** [comment] 2019-07-04 10:31
still running?

**Comment by DaWe35** [comment] 2019-07-04 10:32
Yeah

**Comment by bithon** [comment] 2019-07-04 10:35
great! thanks for info!

**Comment by bithon** [comment] 2019-07-12 13:23
hi DaWe35!

How's it going?

**Comment by DaWe35** [comment] 2019-07-13 14:31
Works perfectly :)

**Comment by bithon** [comment] 2019-07-13 14:37
Great! I am closing this issue!
Best regards!

**Closed by bithon** 2019-07-13 14:37 UTC
Labels: bug
